### ISSUE TITLE
Used in a directive - generation at the same milisecond

### ISSUE THREAD

**Issue by odroz** [sachinchoolur/ngclipboard#13]
Hi Sachin, 
Thanks for this great work!
I used your script in a directive that is used many times on my page. It appears that my copy buttons had weird behavior when 2 buttons were rendered at the same milisecond.
In order to fix that, I changed:
attr("id","ngclipboard"+Date.now())
to
attr("id","ngclipboard"+Math.round(Math.random() \* 1000000))

Hope this helps someone!

**Comment by sachinchoolur** [comment]
Hi,
The issue has already been fixed. Please upgrade to latest version of ngclipboard.
