### ISSUE TITLE
IIFE

### ISSUE THREAD

**Issue by bojank** [sachinchoolur/ngclipboard#14]
the IIFE in the dist is messing with minification,
currently it is
(function() { }()); 
should be
(function() { })();

**Comment by sivalumotune** [comment]
Made a pull request for this.

**Comment by sachinchoolur** [comment]
Thank you guys.
I have merged the PR.

**Comment by joostvunderink** [comment]
It would be great if you could also make a 1.1.2 release with this fix. We want to use your module, but we can't, because it doesn't handle minification well. Thanks!
