### ISSUE TITLE
ctrl+c not working on Safari

### ISSUE THREAD

**Issue by beyondsanity** [sachinchoolur/ngclipboard#15]
Hi, 

Using Safari the library send out the error event correctly, but it doesn't seem to copy the text if i use cmd-C combination. Even the online example doesn't seem to work.
I'm using the "data-clipboard-text" attribute and Safari 9.0.3 for Mac.

**Comment by mgustafsson1** [comment]
@beyondsanity Were you able to get this working?

I can confirm this too. Seems to be something on the Angular side - I tested both with this directive and my own directive, wrapping clipboard.js. No go. It does work with the non Angular version over at https://clipboardjs.com/ though...

Also using the "data-clipboard-text" attribute and Safari 9.0.3 for Mac.

**Comment by beyondsanity** [comment]
@mgustafsson1 sorry for the late response.
I ended up using an hidden textarea (with opacity set to 0) and the "data-clipboard-target" directive attribute.

**Comment by mgustafsson1** [comment]
@beyondsanity Thanks! I'll give that a go...

**Comment by sachinchoolur** [comment]
Hi guys,
Sorry for the delayed response. I've tested this issue on safari and it works fine. Please use the latest version and re-open the issue if it persists..

**Comment by bayy** [comment]
On Safari (Version 9.1.1 (11601.6.17)), the last example
![screen shot 2016-09-19 at 2 04 00 pm](https://cloud.githubusercontent.com/assets/2373656/18647165/f974942a-7e71-11e6-9574-162f5a2f5f51.png)

Only the bottom part works, while the top part does not work.

On the top part, after clicking on "Copy to clipboard" and pressing Command+C, the content of data-clipboard-text is not copied.

From my experience, it seems it only works on Safari when the clipboard text/target is shown. I had to do what @beyondsanity suggested to make it work on Safari.
