### ISSUE TITLE
Tooltip doesn't appear

### ISSUE THREAD

**Issue by ibbatta** [sachinchoolur/ngclipboard#21]
Hi,

there is a specific configuration to show the tooltip? Because I follow your default configuration and, when I copy, the tooltip "copied!" doesn't appear.

Here's my configuration:

```
<button class="btn btn-default btn-xs" ngclipboard data-clipboard-text="{{item.url}}">
   <i class="fa fa-clipboard"></i>
</button>
```

`item.url` is a string that return from a ng-repeat

**Comment by rafaelss95** [comment]
Same here.

**Comment by sachinchoolur** [comment]
You have to add tooltip separately. It doesn't come with ngclipboard.

**Comment by 5achinJani** [comment]
For anyone who comes here looking for the code. 
```html                                                
<button ngclipboard
        data-clipboard-text="Text to be copied"
        uib-tooltip="Copied!"
        tooltip-trigger="'focus'"
        tooltip-popup-close-delay="2000"
        class="btn btn-xs">
                        <i  class="fa fa-clipboard" aria-hidden="true">
                        </i>
</button>
```
Angular bootstrap is needed to use `uib-tooltip`.
