### ISSUE TITLE
Update bindings as "onClipboard" handlers are called?

### ISSUE THREAD

**Issue by jonkri** [sachinchoolur/ngclipboard#3]
Hi!

Thanks for a nice library!

I realized that I had to call $scope.$apply in the "onClipboard" handlers in order to update the bindings. Maybe it would be nice if this library did this for us?

Cheers!

**Comment by sachinchoolur** [comment]
Sorry for the delayed response..
Please provide a plunkr or jsfiddle which demonstrates your problem.

**Comment by jonkri** [comment]
Hi!

Sorry, I don't have time to demonstrate the problem; I just wanted to report that it looked like I had to call $scope.$apply manually in order for the changes I made to the scope to propagate.

Take care!
