### ISSUE TITLE
Any way to use an angular variable in data-clipboard-text?

### ISSUE THREAD

**Issue by jmona789** [sachinchoolur/ngclipboard#36]
Hi, is there any way I can use an angular variable as the data-clipboard-text?  I tried just putting the variable name in there with the curly braces around it but it just copies the name.  I know I can use a hidden input and ng-value but that doesn't work well on mobile.

**Comment by jmona789** [comment]
Nevermind, seems to work now

**Comment by samdbeckham** [comment]
@jmona789 What did you do to fix this? I'm having the same issue
