### ISSUE TITLE
I found that sometimes the ngclipboard will produce the same ID

### ISSUE THREAD

**Issue by Devil-Cong** [sachinchoolur/ngclipboard#4]
Hi!

If I have multiple different elements those binding the ngclipboard in the same page, the ngclipboard sometimes will produce same ID.

Just like ' id="ngclipboard1450668315091" ' appear two times in my program.

**Comment by idanen** [comment]
Hi,
Maybe #5 will solve it.
Can you come up with some reproduction steps? Maybe use [jsfiddle](https://jsfiddle.net/) or something. That way you could test it with the proposed change.

**Comment by sachinchoolur** [comment]
#5 solved it :) Thank you guys
