### ISSUE TITLE
"Module 'ngclipboard' is not available!"

### ISSUE THREAD

**Issue by sabliao** [sachinchoolur/ngclipboard#52]
I included ngclipboard as a dependency for my angular application, but that caused the app to fail after serving the app using `grunt serve:dist`. This is the error
```
Error: [$injector:modulerr] Failed to instantiate module ngclipboard due to:

Error: [$injector:nomod] Module 'ngclipboard' is not available!

You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
I for sure have the right spelling (as you can see from what the error says I used), and I see the ngclipboard code in the generated vendor file. What could be the issue?

**Comment by marcoshmendes** [comment]
Same problem here

**Edit**

The problem was the import, i was importing **clipboard/dist/clipboard.min.js** 2 times, instead of **ngclipboard/dist/ngclipboard.min.js**
