### ISSUE TITLE
Copy from model 

### ISSUE THREAD

**Issue by TheSachin** [sachinchoolur/ngclipboard#6]
hi,
I think it is fairly common for angular devs to manipulate models rather than html string ,can we have feature in which we copy rather a model's value than some html?

**Comment by AlexanderKozhevin** [comment]
+1. I wish it was possible to run make it from controller. Technically I can do it now, but only via emulation button click from javascript.

**Comment by AlexanderKozhevin** [comment]
https://github.com/omichelsen/angular-clipboard
This library is better.

**Comment by sachinchoolur** [comment]
Hi,
Currently this feature is not available. I will let you know if i include this..
