### ISSUE TITLE
Clipboard is not a function?

### ISSUE THREAD

**Issue by javalight** [sachinchoolur/ngclipboard#7]
line 26 console error in ngclipboard.js

**Comment by ruby232** [comment]
If you add the js manualmente, need to add this dependencie https://zenorocha.github.io/clipboard.js/  before del js "ngclipboard.js".

**Comment by Lokua** [comment]
Clipboad.js should be included in bundled ngclipboard dist IMO. In any case including that needed information on ngclipboard website would save developers some time. Cheers.
