### ISSUE TITLE
Not spported in mobile?

### ISSUE THREAD

**Issue by cnlon** [sachinchoolur/ngclipboard#8]
It can run correctly in desktop, but not in mobile?

Is clipboard's problem?

**Comment by vladb95** [comment]
This is beta-version of directive, I'll fix this problem in next version

**Comment by sachinchoolur** [comment]
Hi,
It works fine on all mobile browsers except safari..

**Comment by m00s** [comment]
@sachinchoolur do you plan to support also Safari? Is there any way to fix that?
